# Generated by Django 4.2.16 on 2024-11-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['id'], 'verbose_name_plural': 'member'},
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
