# Generated by Django 4.2.16 on 2025-05-27 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='latest_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messenger.message'),
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('room', 'member')},
        ),
    ]
