name: Django CI

on:
  push:
    branches:
      - staging  # Adjust this if your default branch is different
  pull_request:
    branches:
      - staging  # Runs the workflow on pull requests to the main branch

jobs:
  test_and_lint:
    runs-on: ubuntu-latest  # You can change the runner if necessary

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust Python version if necessary

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest isort flake8

      - name: Run Django tests with pytest
        run: |
          pytest --ds=sparrow.settings  # Adjust the settings path if needed

      - name: Check import order with isort
        run: |
          isort --check .
